---
apiVersion: v1
kind: Service
metadata: 
  name: frontend
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
      #    nodePort: 31004  # Optional: Specify a nodePort if you want a fixed port
  selector:
    app: frontend  # Ensure this matches the labels in the Deployment
  type: LoadBalancer

